### PR TITLE
applications: asset_tracker: set CONFIG_INIT_ARCH_HW_AT_BOOT for SPM

### PR DESCRIPTION
**Pull request by rlubos**
Same as in the core SPM config file.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
LGTM.
Now I wonder if this should be at the SPM subsystem Kconfig as default y, to minimize configuration changes.

**Comment by ioannisg** [comment]
@hakonfam please review this patch.

**Comment by ioannisg** [comment]
I also wonder if we need a similar fix for the UDP sample.

**Comment by ioannisg** [comment]
> I also wonder if we need a similar fix for the UDP sample.

@hakonfam ^^

**Comment by hakonfam** [comment]
Will check it tomorrow

**Pull request merged**
